// This file is generated by npm run build:icons

export type IconName =
	| 'arrow-left-outline'
	| 'brand-github-outline'
	| 'brand-linkedin-outline'
	| 'brand-x-outline'
	| 'brand-youtube-outline'
	| 'check-outline'
	| 'download-outline'
	| 'refresh-outline'
	| 'x-outline'
